import "./globals.css";
import Provider from "./provider";
export const metadata = {
  title: "Hey Buildex",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <Provider />
      </body>
    </html>
  );
}
